# Generated by Django 5.2.7 on 2025-11-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_libro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='Nada', max_length=255),
            preserve_default=False,
        ),
    ]
