# Generated by Django 5.2.7 on 2025-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='library_id',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
