# Generated by Django 5.2.7 on 2025-11-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_libro_favorito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='favorito',
            new_name='favoritos',
        ),
    ]
